### ISSUE TITLE
Transform Feedback 

### ISSUE THREAD

**Issue by yalcinmelihyasin** [google/vulkan_test_applications#206]
Transform Feedback sample crashes on a supported device.  

Stack:

art_sigsegv_fault 0x0000007047a3d1c0
art::FaultManager::HandleFault(int, siginfo*, void*) 0x0000007047a3d6d4
art::SignalChain::Handler(int, siginfo*, void*) 0x0000005d77531e64
<unknown> 0x00000072df8f1678
vkCmdBeginTransformFeedbackEXT 0x0000007024d8bb38
vkCmdBeginTransformFeedbackEXT 0x0000007024d8bb38
std::__ndk1::result_of<void (* (vulkan::VkCommandBuffer, int, int, std::nullptr_t, std::nullptr_t))(VkCommandBuffer_T*, unsigned int, unsigned int, VkBuffer_T* const*, unsigned long const*)>::type LazyFunction<void (*)(VkCommandBuffer_T*, unsigned int, unsigned int, VkBuffer_T* const*, unsigned long const*), VkDevice_T*, vulkan::DeviceFunctions>::operator()<vulkan::VkCommandBuffer, int, int, std::nullptr_t, std::nullptr_t>(vulkan::VkCommandBuffer const&, int const&, int const&, std::nullptr_t const&, std::nullptr_t const&) 0x0000006fd2502dc8
TransformFeedbackSample::Render(vulkan::VkQueue*, unsigned long, TransformFeedbackFrameData*) 0x0000006fd24d7eb8
sample_application::Sample<TransformFeedbackFrameData>::ProcessFrame() 0x0000006fd24d640c
main_entry(entry::EntryData const*) 0x0000006fd24d4f60
<unknown> 0x0000006fd2563f78
<unknown> 0x0000006fd2563ddc
<unknown> 0x0000006fd2563d3c
<unknown> 0x0000006fd25636d4
__pthread_start(void*) 0x00000072da80a12c
__start_thread 0x00000072da7aa610

**Comment by AWoloszyn** [comment]
Do you have any information from the vulkan validation layers as to what the issue may be?
This is a crash inside of the driver, so it would be good to see what the validation layers say we are doing wrong.

**Comment by AWoloszyn** [comment]
Since this works (and did without validation issues) elsewhere, I am going to assume this is a device driver bug without any more information. Please re-open if you can repro with more info.
