### ISSUE TITLE
Cmake usage of `COPY_ONLY` not valid for `configure_file` i.e. `COPYONLY` is

### ISSUE THREAD

**Issue by Crog** [google/vulkan_test_applications#210]
If you search for `configure_file` Cmake calls there are a couple that use `COPY_ONLY` but the documented option is wihtout the '_' . See here https://cmake.org/cmake/help/latest/command/configure_file.html

**Comment by krmoule** [comment]
Thanks for pointing this out! A fix should be in place soon.
